export const apiUrl = {
  login: "auth/login",
  LogOut: "auth/logout",
  me: "auth/me",
  updateProfile: "auth/profile",
  getAllPropertiesListing: "admin/properties",
  syncProperties: "admin/properties/sync",
  updatePropertyStatus: "admin/properties",
  getPropertyById: "admin/properties",
  getAllPricingMarkups: "admin/pricing-markups",
  getPricingMarkupById: "admin/pricing-markups",
  togglePricingMarkupStatus: "admin/pricing-markups",
  deletePricingMarkup: "admin/pricing-markups",
  setDefaultMarkup: "admin/pricing-markups/set-default",
};
